# Generated by Django 2.2.9 on 2020-01-29 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_content_html'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ('-pk',)},
        ),
    ]
